version: "3"

services:
  server:
    image: apozdniakov/tricky-compression:1.0.0
    restart: always
    ports:
      - "1337:8080"
    volumes:
      - file_storage:/file_storage/

volumes:
  file_storage:
